name: meal_planner
description: A comprehensive meal planning app with nutrition tracking, recipe discovery, and health analytics.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_app_check: ^0.3.1

  
  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # Camera & Image
  camera: ^0.11.1
  image_picker: ^1.1.2
  
  # HTTP & API
  http: ^1.2.2

  # GOOGLE ML KIT
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_image_labeling: ^0.14.1
  image: ^4.1.7
  path_provider: ^2.1.3

  # Local Storage
  shared_preferences: ^2.3.2

  # Utilities
  intl: ^0.20.2

  openapi:
    path: C:\spoonacular_api

  # Firebase Auth (Blaze Plan)
  cloud_functions: ^5.1.3

# OVERRIDE BOTH CONFLICTING DEPENDENCIES
dependency_overrides:
  intl: ^0.18.1
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/